import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ThemeContextProvider from "@/context/theme";
import { ThemeWrapper } from "@/components/ThemeWrapper";
import GlobalContextProvider from "@/context/global";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalContextProvider>

          <ThemeContextProvider>
          
            <ThemeWrapper>

            <Navbar />
             {children}
           </ThemeWrapper>
           <Toaster />
          </ThemeContextProvider>
        </GlobalContextProvider>

      </body>
    </html>
  );
}
